FORMAT: 1A
HOST: http://localhost:3333

# Group Youtube Downloader

## Download a video [/videos]
### Download a video [POST]
+ Response 200 (application/json)
    {
        "download": "http://localhost:3333/downloads/videos/didnadndsaodsak.mp3",
        "size": 2856322,
        "message": "Your video processing is done! You just need to download it clicking on the button below!"
    }
+ Parameters
    + Note: This params are on the body :) (string) - Do not use this param this is just a note that i am leaving for you 
    + video_url: https://www.youtube.com/watch?v=d98di8hidesh (string) - Video url that you want to download
    + convert_to: mp3 | mp4 (string, optional) - The video format that you want to download
        + Default: mp3
    + deleted_videos: [7, 45, 13, 23] (array, optional) - This parameter only accepts an array of numbers with the videos indexes that you DONT wanna download(if the videos that you dont wanna download are the 1st and the 6th then the array is gonna be: [1, 6] )
        + Default: []
    + compress: true (boolean, optional) - If you want to compress the whole playlist in a unique file the set it as true, the compression DO NOT remove a lot of the mb from the original size
        + Default: false
    


## Download a playlist [/playlists]
### Download a playlist [POST]
+ Response 200 (application/json)
    {
        "filename": "djnsaudsaubjdcu___PlaylistName.zip",
        "download": "http://localhost:3333/downloads/playlist/0faa2b11a3999a10844bafd657e93593___Piano.zip", // Download Link
        "size": 32812179, // File Size in bytes
        "message": "Your playlist is gonna be downloaded in few minutes, go get some coffee :)"
    }
+ Parameters
    + Note: This params are on the body :) (string) - Do not use this param this is just a note that i am leaving for you 
    + playlist_url: https://www.youtube.com/playlist?list=d98di8hidesh (string) - Playlist url that you want to download
    + playlist_name: My songs (string) - This name will be the same as the folder that the videos are in
    + convert_to: mp3 | mp4 (string, optional) - The videos formats that you want to download
        + Default: mp3